### ISSUE TITLE
Exercise 1: plot retained data also

### ISSUE THREAD

**Issue by rgcoe** [ec-benchmark-organizers/ec-benchmark#4]
In [`plot_benchmark_contours_dataset_abc.py`](https://github.com/ec-benchmark-organizers/ec-benchmark/blob/master/results/exercise-1/plot_benchmark_contours_dataset_abc.py) and [`plot_benchmark_contours_dataset_def.py`](https://github.com/ec-benchmark-organizers/ec-benchmark/blob/master/results/exercise-1/plot_benchmark_contours_dataset_def.py), we do not currently plot the retained data.

I made a version of our plotting script that did this previously here: https://github.com/ec-benchmark-organizers/ec-benchmark/commit/78cf82957098d0d068f1b6b3017f374701bdad13, so really just a matter of copy-pasting into the current versions of the code.

**Comment by rgcoe** [comment]
completed with 260929e 
![Figure_1](https://user-images.githubusercontent.com/5589887/94039114-865d6700-fd84-11ea-8267-4c72c64f0e12.png)

@ahaselsteiner - what do you think about using empty markers for the retained data (as below)? To me, this makes it easier to distinguish.
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/5589887/94039540-169bac00-fd85-11ea-9b3d-3d568fee27b4.png">

**Comment by ahaselsteiner** [comment]
@ryancoe Good idea. I updated the script and replaced the figures in the overleaf document.

**Comment by ahaselsteiner** [comment]
As this is done, I'm closing the issue.
